name: InviteTree
version: '${project.version}'
main: dev.advik.invitetree.InviteTree
api-version: '1.20'
description: 'A plugin that allows you to invite players to your SMP.'
commands:
  inviteDebug:
    description: 'Debug command for InviteTree'
    usage: '/inviteDebug'
    permission: 'invitetree.invitedebug'
  salt:
    description: 'Salt command for InviteTree'
    usage: '/salt'
    permission: 'invitetree.salt'