name: InviteTree
version: '1.0-SNAPSHOT'
main: dev.advik.InviteTree.InviteTree
api-version: '1.21'
load: STARTUP
authors: [ Advik ]
#commands:
#  invite:
#    description: Invite a player to play on the server
#    usage: /invite <player>
#    permission: invitetree.invite
#  invites:
#    description: List all the players you have invited or another player has invited
#    usage: /invites [player]
#    permission: invitetree.invites.self
#    permission-message: You do not have permission to use this command.
#  tree:
#    description: List all the players invited (ever)
#    usage: /tree
#    permission: invitetree.tree
#    permission-message: You do not have permission to use this command.
#  banbranch:
#    description: Ban a player and all the players invited by them
#    usage: /banbranch <player>
#    permission: invitetree.banbranch
#  kickbranch:
#    description: Kick a player and all the players invited by them
#    usage: /kickbranch <player>
#    permission: invitetree.kickbranch
#  branch:
#    description: List all the players invited by a player
#    usage: /branch <player>
#    permission: invitetree.branch.self
#    permission-message: You do not have permission to use this command.
#
#
#permissions:
#  invitetree.invite:
#    description: Allows a player to invite others
#    default: true
#  invitetree.invites.self:
#    description: Allows a player to view their own invites
#    default: true
#  invitetree.invites.all:
#    description: Allows a player to view invites of other players
#    default: op
#  invitetree.tree:
#    description: Allows to view the invite tree
#    default: op
#  invitetree.branch.self:
#    description: Allows a player to view the branch of themselves
#    default: true
#  invitetree.branch.all:
#    description: Allows a player to view the branch of other players
#    default: op
#  invitetree.banbranch:
#    description: Allows banning a player and their invitees
#    default: op
#  invitetree.kickbranch:
#    description: Allows kicking a player and their invitees
#    default: op
