name: InviteTree
version: '${project.version}'
main: dev.advik.invitetree.InviteTree
api-version: '1.20'
description: 'A plugin that adds an advanced invite system to your server with a lot of features.'
database: true
author: Advik-B